/**
 * Type definitions for SlopBlock extension
 * Based on the Supabase database schema
 */

/**
 * Video record from database
 */
export interface Video {
  video_id: string;
  channel_id: string | null;
  report_count: number;
  first_reported_at: string;
  last_reported_at: string;
  created_at: string;
  updated_at: string;
}

/**
 * Individual report record
 */
export interface Report {
  id: number;
  video_id: string;
  extension_id: string;
  trust_weight: number; // 0.30 to 1.00
  accuracy_status: 'pending' | 'accurate' | 'inaccurate'; // Evaluated after 30 days
  accuracy_evaluated_at: string | null;
  reported_at: string;
}

/**
 * Extension trust record (Phase 3 - Enhanced Hybrid Model + Cold-Start)
 */
export interface ExtensionTrust {
  extension_id: string;
  trust_score: number; // 0.00 to 1.00 (hybrid: 50% time + 50% accuracy + pioneer_boost)
  first_seen: string;
  last_active: string;
  total_reports: number;
  total_removed_reports: number;
  // Accuracy tracking (prevents botnet attacks)
  accurate_reports: number; // Reports that led to threshold being reached
  inaccurate_reports: number; // Reports on videos that never reached threshold
  pending_reports: number; // Reports still in 30-day evaluation window
  accuracy_rate: number; // 0.00 to 1.00 (accurate / total_evaluated)
  // Cold-start solution
  pioneer_boost: number; // 0.00 to 0.50 (permanent bonus for early adopters)
  user_number: number | null; // Registration sequence (1st user, 2nd user, etc.)
  is_flagged: boolean;
  flagged_reason: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * Video aggregate cache record (Phase 3 - CDN ready, Cold-Start)
 */
export interface VideoAggregateCache {
  video_id: string;
  channel_id: string;
  effective_trust_points: number; // Sum of trust-weighted reports
  raw_report_count: number;
  is_marked: boolean; // effective_trust_points >= dynamic threshold (from community_stats)
  first_reported_at: string;
  last_updated_at: string;
  cache_version: number;
}

/**
 * Community maturity stats (Phase 3 - Cold-Start Solution)
 * Used to calculate dynamic threshold based on community growth
 */
export interface CommunityStats {
  id: number; // Always 1 (single row table)
  total_users: number; // Total unique extension installations
  active_users_30d: number; // Users who reported in last 30 days
  avg_trust_weight: number; // Average trust weight of active users
  maturity_factor: number; // Normalized maturity (avg_trust / 0.75)
  effective_threshold: number; // Current dynamic threshold (2.5 × maturity_factor)
  last_updated: string;
  created_at: string;
}

/**
 * Cache metadata (Phase 4 - CDN cache system)
 */
export interface CacheMetadata {
  key: string;
  last_sync_timestamp: string;
  last_prune_timestamp: string;
  blob_version: string;
}

/**
 * Queued report for IndexedDB (Phase 3)
 */
export interface QueuedReport {
  id?: number; // Auto-generated by IndexedDB
  video_id: string;
  channel_id: string;
  extension_id: string;
  queued_at: number; // Timestamp
  retry_count: number;
  last_error?: string;
}

/**
 * Response from report_video function
 */
export interface ReportVideoResponse {
  success: boolean;
  video_id: string;
  report_count: number;
  is_new_report: boolean;
}

/**
 * Response from remove_report function
 */
export interface RemoveReportResponse {
  success: boolean;
  video_id?: string;
  report_count?: number;
  error?: string;
}

/**
 * Response from check_user_report function
 */
export interface CheckUserReportResponse {
  video_id: string;
  has_reported: boolean;
  report_count: number;
}

/**
 * Response from get_channel_stats function
 */
export interface ChannelStatsResponse {
  channel_id: string;
  marked_video_count: number;
  total_reports: number;
}

/**
 * Response from get_user_stats function
 */
export interface UserStatsResponse {
  extension_id: string;
  user_reports: number;
  total_marked_videos: number;
}

/**
 * Marked video data (from get_marked_videos)
 * LEGACY: Use MarkedVideoWeighted for Phase 3+
 */
export interface MarkedVideo {
  video_id: string;
  report_count: number;
  channel_id: string | null;
}

/**
 * Marked video data with trust weighting (Phase 3+)
 */
export interface MarkedVideoWeighted {
  video_id: string;
  channel_id: string;
  effective_trust_points: number; // Replaces report_count
  raw_report_count: number;
  first_reported_at: string;
}

/**
 * Response from batch_report_videos function (Phase 3)
 * Column names prefixed with "out_" to avoid PostgreSQL ambiguity
 */
export interface BatchReportResult {
  out_video_id: string;
  out_success: boolean;
  out_effective_trust_points: number;
  out_is_marked: boolean;
  out_error_message: string | null;
}

/**
 * Response from check_user_report_weighted function (Phase 3)
 */
export interface CheckUserReportWeightedResponse {
  has_reported: boolean;
  trust_weight: number;
  reported_at: string | null;
}

/**
 * Cached video data stored in extension
 */
export interface CachedVideoData {
  video_id: string;
  report_count: number;
  channel_id: string | null;
  cached_at: number; // Timestamp
}

/**
 * Extension storage structure
 */
export interface ExtensionStorage {
  [key: string]: any;
  slopblock_extension_id?: string;
  slopblock_auto_hide?: boolean;
  slopblock_video_cache?: Record<string, CachedVideoData>;
}

/**
 * Message types for communication between content script and background worker
 */
export enum MessageType {
  REPORT_VIDEO = 'REPORT_VIDEO',
  REMOVE_REPORT = 'REMOVE_REPORT',
  CHECK_VIDEOS = 'CHECK_VIDEOS',
  GET_CHANNEL_STATS = 'GET_CHANNEL_STATS',
  CHECK_USER_REPORT = 'CHECK_USER_REPORT',
  GET_USER_STATS = 'GET_USER_STATS',
  // Phase 3 additions
  BATCH_REPORT_VIDEOS = 'BATCH_REPORT_VIDEOS',
  CHECK_VIDEOS_WEIGHTED = 'CHECK_VIDEOS_WEIGHTED',
  CHECK_USER_REPORT_WEIGHTED = 'CHECK_USER_REPORT_WEIGHTED',
  GET_TRUST_SCORE = 'GET_TRUST_SCORE',
  QUEUE_REPORT = 'QUEUE_REPORT', // Queue a single report (background worker handles it)
  REMOVE_QUEUED_REPORT = 'REMOVE_QUEUED_REPORT', // Remove a report from queue (or from DB if already uploaded)
  GET_QUEUE_SIZE = 'GET_QUEUE_SIZE', // Get current queue size for stats display
  SET_UPLOAD_INTERVAL = 'SET_UPLOAD_INTERVAL', // Update upload interval (testing only)
  // Phase 3 cold-start additions
  GET_COMMUNITY_STATS = 'GET_COMMUNITY_STATS',
  // Phase 4 CDN cache additions
  REFRESH_CACHE = 'REFRESH_CACHE',
  DELTA_SYNC = 'DELTA_SYNC',
  GET_CACHE_METADATA = 'GET_CACHE_METADATA',
  GET_CACHED_VIDEO_COUNT = 'GET_CACHED_VIDEO_COUNT',
  CLEAR_CACHE = 'CLEAR_CACHE',
  // Settings management (IndexedDB via service worker)
  GET_AUTO_HIDE_SETTING = 'GET_AUTO_HIDE_SETTING',
  SET_AUTO_HIDE_SETTING = 'SET_AUTO_HIDE_SETTING',
}

/**
 * Message structure for chrome.runtime.sendMessage
 */
export interface ExtensionMessage<T = any> {
  type: MessageType;
  payload: T;
}

/**
 * Payload for REPORT_VIDEO message
 */
export interface ReportVideoPayload {
  video_id: string;
  channel_id: string;
}

/**
 * Payload for REMOVE_REPORT message
 */
export interface RemoveReportPayload {
  video_id: string;
}

/**
 * Payload for CHECK_VIDEOS message
 */
export interface CheckVideosPayload {
  video_ids: string[];
}

/**
 * Payload for GET_CHANNEL_STATS message
 */
export interface GetChannelStatsPayload {
  channel_id: string;
}

/**
 * Payload for CHECK_USER_REPORT message
 */
export interface CheckUserReportPayload {
  video_id: string;
}

/**
 * Payload for BATCH_REPORT_VIDEOS message (Phase 3)
 */
export interface BatchReportVideosPayload {
  reports: Array<{
    video_id: string;
    channel_id: string;
    extension_id: string;
  }>;
}

/**
 * Payload for CHECK_VIDEOS_WEIGHTED message (Phase 3)
 */
export interface CheckVideosWeightedPayload {
  video_ids: string[];
}

/**
 * Payload for GET_TRUST_SCORE message (Phase 3)
 */
export interface GetTrustScorePayload {
  extension_id: string;
}

/**
 * Payload for SET_AUTO_HIDE_SETTING message (Phase 4)
 */
export interface SetAutoHideSettingPayload {
  enabled: boolean;
}

/**
 * Response structure for messages
 */
export interface MessageResponse<T = any> {
  success: boolean;
  data?: T;
  error?: string;
}
